name: 'Bundle name'
description: 'Returns the name of the release'
outputs:
  BUNDLE:
    description: "Bundle"
    value: ${{ steps.bundlestep.outputs.BUNDLE }}
runs:
  using: "composite"
  steps:
    - id: bundlestep
      run: echo "::set-output BUNDLE=$(./scripts/bundle.sh)::true"
      shell: bash
