name: 'Bundle name'
description: 'Returns the name of the release'
outputs:
  BUNDLE:
    description: "Bundle"
    value: ${{ steps.bundlestep.outputs.BUNDLE }}
runs:
  using: "composite"
  steps:
    - id: bundlestep
      run: |
        TITLE=$(git show -s --format='%h')
        SHORT_SHA=$(git show -s --format='%s')
        echo "BUNDLE=$("$TITLE $SHORT_SHA" \
          | sed "s/['\"]//g" \
          | tr '[:upper:]' '[:lower:]' \
          | sed "s/[ \n\t]/-/g" \
          | sed 's/-$//' \
          | sed 's/\./-/' \
          | sed 's/[^a-z0-9_\-]//g')" >> $GITHUB_OUTPUT
