name: 'Bundle name'
description: 'Returns the name of the release'
outputs:
  BUNDLE:
    description: "Bundle"
    value: ${{ steps.bundlestep.outputs.BUNDLE }}
runs:
  using: "composite"
  steps:
    - run: TITLE=$(git show -s --format='%h')
      shell: bash
    - run: SHORT_SHA=$(git show -s --format='%s')
      shell: bash
    - id: bundlestep
      run: |
        echo "BUNDLE=$(echo "$TITLE $SHORT_SHA" | sed "s/['\"]//g" | tr '[:upper:]' '[:lower:]' | sed "s/[ \n\t]/-/g" | sed 's/-$//' | sed 's/\./-/' | sed 's/[^a-z0-9_\-]//g')" >> $GITHUB_OUTPUT
      shell: bash
