name: 'Bundle name'
description: 'Returns the name of the release'
outputs:
  bundle:
    description: "Bundle"
    value: ${{ steps.random-number-generator.outputs.bundle }}
runs:
  using: "composite"
  steps:
    - run: echo "bundle=$(./scripts/bundle.sh)" >> $GITHUB_OUTPUT
      shell: bash
