name: 'Bundle name'
description: 'Returns the name of the release'
outputs:
  bundle:
    description: "Bundle"
    value: ${{ steps.bundlestep.outputs.bundle }}
runs:
  using: "composite"
  steps:
    - id: bundlestep
      run: echo "bundle=$(./scripts/bundle.sh)" >> $GITHUB_OUTPUT
      shell: bash
