on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: QuiqueBarberan/bundlename@master
        id: stepbundle
      - run: echo "${{ steps.stepbundle.outputs.BUNDLE }}"
        shell: bash
